package com.shdata.datachain.catalog.browse;

import java.time.Instant;
import java.util.List;
import java.util.Map;

/**
 * 目录产品（列表/预览/详情/编辑共用字段）。
 *
 * <p>V1.1：产品挂载点为三级（{@code l3CategoryId}）；保留 {@code l1}/{@code l2} 便于筛选。
 * 兼容构造器（无 l3）供 editor 等尚未切换的写路径编译；缺省 {@code l3CategoryId=null}。
 */
public record CatalogProduct(
    String id,
    String productCode,
    String productName,
    String productType,
    String l2CategoryId,
    String l1CategoryId,
    String categoryPath,
    int chainCount,
    Integer latestVersionNo,
    String dataSource,
    String deliveryMethod,
    Boolean involvesPublicData,
    Boolean involvesPersonalInfo,
    String summary,
    String scenario,
    String supplierName,
    String supplierCreditCode,
    List<String> tags,
    Map<String, Object> typeSpecific,
    String businessCategory,
    String businessSubCategory,
    String updateFrequency,
    String billingMethod,
    String price,
    String propertyRightsType,
    String l3CategoryId,
    Instant updatedAt) {

  /** 兼容无三级挂载的旧构造（editor 等）。 */
  public CatalogProduct(
      String id,
      String productCode,
      String productName,
      String productType,
      String l2CategoryId,
      String l1CategoryId,
      String categoryPath,
      int chainCount,
      Integer latestVersionNo,
      String dataSource,
      String deliveryMethod,
      Boolean involvesPublicData,
      Boolean involvesPersonalInfo,
      String summary,
      String scenario,
      String supplierName,
      String supplierCreditCode,
      List<String> tags,
      Map<String, Object> typeSpecific,
      String businessCategory,
      String businessSubCategory,
      String updateFrequency,
      String billingMethod,
      String price,
      String propertyRightsType) {
    this(
        id,
        productCode,
        productName,
        productType,
        l2CategoryId,
        l1CategoryId,
        categoryPath,
        chainCount,
        latestVersionNo,
        dataSource,
        deliveryMethod,
        involvesPublicData,
        involvesPersonalInfo,
        summary,
        scenario,
        supplierName,
        supplierCreditCode,
        tags,
        typeSpecific,
        businessCategory,
        businessSubCategory,
        updateFrequency,
        billingMethod,
        price,
        propertyRightsType,
        null,
        null);
  }

  /** 兼容无 {@code updatedAt} 的构造。 */
  public CatalogProduct(
      String id,
      String productCode,
      String productName,
      String productType,
      String l2CategoryId,
      String l1CategoryId,
      String categoryPath,
      int chainCount,
      Integer latestVersionNo,
      String dataSource,
      String deliveryMethod,
      Boolean involvesPublicData,
      Boolean involvesPersonalInfo,
      String summary,
      String scenario,
      String supplierName,
      String supplierCreditCode,
      List<String> tags,
      Map<String, Object> typeSpecific,
      String businessCategory,
      String businessSubCategory,
      String updateFrequency,
      String billingMethod,
      String price,
      String propertyRightsType,
      String l3CategoryId) {
    this(
        id,
        productCode,
        productName,
        productType,
        l2CategoryId,
        l1CategoryId,
        categoryPath,
        chainCount,
        latestVersionNo,
        dataSource,
        deliveryMethod,
        involvesPublicData,
        involvesPersonalInfo,
        summary,
        scenario,
        supplierName,
        supplierCreditCode,
        tags,
        typeSpecific,
        businessCategory,
        businessSubCategory,
        updateFrequency,
        billingMethod,
        price,
        propertyRightsType,
        l3CategoryId,
        null);
  }
}
